<?php

namespace Simplon\ActiviteGiteBundle\Repository;

/**
 * GestionnaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GestionnaireRepository extends \Doctrine\ORM\EntityRepository
{
}
