<?php

namespace Simplon\ActiviteGiteBundle\Repository;

/**
 * GitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GitesRepository extends \Doctrine\ORM\EntityRepository
{
}
